version: '3'
services:
    ofelia:
        image: mcuadros/ofelia:latest
        container_name: ofelia
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
    rsync-backup-job:
        image: instrumentisto/rsync-ssh:latest
        container_name: rsync_worker_backup
        restart: "unless-stopped"
        entrypoint: ["tail", "-f", "/dev/null"]
        volumes:
            - ${BACKUP_SOURCE}:/data/source:ro
            - ${BACKUP_TARGET}:/data/target
        labels:
            ofelia.enabled: "true"
            ofelia.job-exec.sync-folders.schedule: ${BACKUP_SCHEDULER}
            ofelia.job-exec.sync-folders.command: "rsync -av --delete --no-perms --no-owner --no-group /data/source/ /data/target/"
    heimdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        restart: unless-stopped
        ports:
            - "${HEIMDALL_PORT_HTTP}:80"
            - "${HEIMDALL_PORT_HTTPS}:443"
        volumes:
            - ${BASE_DIR}/heimdall/config:/config
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: unless-stopped
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "${PIHOLE_PORT_HTTP}:80"
            - "${PIHOLE_PORT_HTTPS}:443"
        environment:
            - TZ=${TZ}
            - FTLCONF_webserver_api_password:${PIHOLE_ADMIN_PASSWORD}
            - FTLCONF_dns_listeningMode:all
        volumes:
            - ${BASE_DIR}/pihole/etc/pihole:/etc/pihole
            - ${BASE_DIR}/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
        dns:
            - 1.1.1.2
            - 1.1.1.1
        cap_add:
            - SYS_NICE
            - SYS_TIME
    node-red:
        image: nodered/node-red:latest
        container_name: node-red
        restart: unless-stopped
        environment:
            - TZ=${TZ}
        ports:
            - "${NODE_RED_PORT}:1880"
        volumes:
            - ${BASE_DIR}/node-red/data:/data
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        restart: unless-stopped
        environment:
            - TZ=${TZ}
        ports:
            - "${INFLUXDB_PORT}:8086"
        volumes:
            - ${BASE_DIR}/influxdb/var/lib/influxdb2:/var/lib/influxdb2
    duckdns:
        image: lscr.io/linuxserver/duckdns:latest
        container_name: duckdns
        restart: unless-stopped
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
            - TOKEN=${DUCKDNS_TOKEN}
            - UPDATE_IP=ipv4
            - LOG_FILE=false
        volumes:
            - ${BASE_DIR}/duckdns/config:/config
    diun:
        image: crazymax/diun:latest
        container_name: diun
        restart: unless-stopped
        command: serve
        environment:
            - TZ=${TZ}
            - DIUN_WATCH_WORKERS=20
            - DIUN_WATCH_SCHEDULE=${DIUN_SCHEDULER}
            - DIUN_WATCH_JITTER=30s
            - DIUN_PROVIDERS_DOCKER=true
            - DIUN_NOTIF_TELEGRAM_TOKEN=${DIUN_TELEGRAM_TOKEN}
            - DIUN_NOTIF_TELEGRAM_CHATIDS=${DIUN_TELEGRAM_CHATID}
        volumes:
            - ${BASE_DIR}/diun/data:/data"
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "diun.enable=true"
