services:
    nebula-sync:
        image: ghcr.io/lovelaze/nebula-sync:v0.11.2
        container_name: nebula-sync
        restart: unless-stopped
        environment:
            - TZ=${TZ}
            - CRON=${NEBULA_SYNC_CRON}
            - FULL_SYNC=${NEBULA_SYNC_FULL}
            - RUN_GRAVITY=${NEBULA_SYNC_GRAVITY}
            - CLIENT_SKIP_TLS_VERIFICATION=${NEBULA_SYNC_SKIP_TLS}
            - PRIMARY=${NEBULA_SYNC_PRIMARY}
            - REPLICAS=${NEBULA_SYNC_REPLICAS}
            - WEBHOOK_SYNC_SUCCESS_URL=${NEBULA_SYNC_WEBHOOK_OK}
            - WEBHOOK_SYNC_FAILURE_URL=${NEBULA_SYNC_WEBHOOK_FAIL}
        networks:
            - homeserver

networks:
    homeserver:
        external: true
